// <auto-generated />
using System;
using DumpsterLeagueLeaderboard.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DumpsterLeagueLeaderboard.Infrastructure.Migrations.ApplicationWrite
{
    [DbContext(typeof(ApplicationWriteContext))]
    [Migration("20260212074728_AddEventAndSeasonToPointTable")]
    partial class AddEventAndSeasonToPointTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DumpsterLeagueLeaderboard.Domain.Entities.Leaderboard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("leaderboard_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentPoints")
                        .HasColumnType("integer")
                        .HasColumnName("current_points");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<bool>("IsDisqualified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disqualified");

                    b.Property<DateTime>("LeaderboardDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("leaderboard_date");

                    b.Property<Guid>("LeagueEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_event_id");

                    b.Property<int>("Placement")
                        .HasColumnType("integer")
                        .HasColumnName("placement");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int>("PointsGained")
                        .HasColumnType("integer")
                        .HasColumnName("points_gained");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid")
                        .HasColumnName("tournament_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("LeagueEventId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("TournamentId");

                    b.ToTable("leaderboards", (string)null);
                });

            modelBuilder.Entity("DumpsterLeagueLeaderboard.Domain.Entities.LeagueEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("league_event_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsOngoing")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ongoing");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("league_events", (string)null);
                });

            modelBuilder.Entity("DumpsterLeagueLeaderboard.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentDiscordId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_discord_id");

                    b.Property<string>("CurrentDiscordName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_discord_name");

                    b.Property<string>("CurrentIgn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_ign");

                    b.Property<int>("CurrentPoints")
                        .HasColumnType("integer")
                        .HasColumnName("current_points");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("DumpsterLeagueLeaderboard.Domain.Entities.PlayerPlacementHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("player_placement_history_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentPoints")
                        .HasColumnType("integer")
                        .HasColumnName("current_points");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<int>("Placement")
                        .HasColumnType("integer")
                        .HasColumnName("placement");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int>("PointsGained")
                        .HasColumnType("integer")
                        .HasColumnName("points_gained");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid")
                        .HasColumnName("tournament_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TournamentId");

                    b.ToTable("player_placement_histories", (string)null);
                });

            modelBuilder.Entity("DumpsterLeagueLeaderboard.Domain.Entities.Point", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("point_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("LeagueEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_event_id");

                    b.Property<int>("PointGained")
                        .HasColumnType("integer")
                        .HasColumnName("point_gained");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("LeagueEventId");

                    b.HasIndex("SeasonId");

                    b.ToTable("points", (string)null);
                });

            modelBuilder.Entity("DumpsterLeagueLeaderboard.Domain.Entities.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<Guid>("LeagueEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_event_id");

                    b.Property<DateTime>("SeasonEndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("season_end_date");

                    b.Property<string>("SeasonName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("season_name");

                    b.Property<DateTime>("SeasonStartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("season_start_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("LeagueEventId");

                    b.ToTable("seasons", (string)null);
                });

            modelBuilder.Entity("DumpsterLeagueLeaderboard.Domain.Entities.Tournament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tournament_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid?>("LeagueEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_event_id");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<string>("StartGgLink")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("start_gg_link");

                    b.Property<DateTime>("TournamentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tournament_date");

                    b.Property<string>("TournamentName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tournament_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("LeagueEventId");

                    b.HasIndex("SeasonId");

                    b.ToTable("tournaments", (string)null);
                });

            modelBuilder.Entity("DumpsterLeagueLeaderboard.Domain.Entities.Leaderboard", b =>
                {
                    b.HasOne("DumpsterLeagueLeaderboard.Domain.Entities.LeagueEvent", "LeagueEvent")
                        .WithMany("Leaderboards")
                        .HasForeignKey("LeagueEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DumpsterLeagueLeaderboard.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DumpsterLeagueLeaderboard.Domain.Entities.Season", "Season")
                        .WithMany("Leaderboards")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DumpsterLeagueLeaderboard.Domain.Entities.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeagueEvent");

                    b.Navigation("Player");

                    b.Navigation("Season");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("DumpsterLeagueLeaderboard.Domain.Entities.PlayerPlacementHistory", b =>
                {
                    b.HasOne("DumpsterLeagueLeaderboard.Domain.Entities.Player", "Player")
                        .WithMany("PlacementHistories")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DumpsterLeagueLeaderboard.Domain.Entities.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("DumpsterLeagueLeaderboard.Domain.Entities.Point", b =>
                {
                    b.HasOne("DumpsterLeagueLeaderboard.Domain.Entities.LeagueEvent", "LeagueEvent")
                        .WithMany()
                        .HasForeignKey("LeagueEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DumpsterLeagueLeaderboard.Domain.Entities.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeagueEvent");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("DumpsterLeagueLeaderboard.Domain.Entities.Season", b =>
                {
                    b.HasOne("DumpsterLeagueLeaderboard.Domain.Entities.LeagueEvent", "LeagueEvent")
                        .WithMany("Seasons")
                        .HasForeignKey("LeagueEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeagueEvent");
                });

            modelBuilder.Entity("DumpsterLeagueLeaderboard.Domain.Entities.Tournament", b =>
                {
                    b.HasOne("DumpsterLeagueLeaderboard.Domain.Entities.LeagueEvent", "LeagueEvent")
                        .WithMany("Tournaments")
                        .HasForeignKey("LeagueEventId");

                    b.HasOne("DumpsterLeagueLeaderboard.Domain.Entities.Season", "Season")
                        .WithMany("Tournaments")
                        .HasForeignKey("SeasonId");

                    b.Navigation("LeagueEvent");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("DumpsterLeagueLeaderboard.Domain.Entities.LeagueEvent", b =>
                {
                    b.Navigation("Leaderboards");

                    b.Navigation("Seasons");

                    b.Navigation("Tournaments");
                });

            modelBuilder.Entity("DumpsterLeagueLeaderboard.Domain.Entities.Player", b =>
                {
                    b.Navigation("PlacementHistories");
                });

            modelBuilder.Entity("DumpsterLeagueLeaderboard.Domain.Entities.Season", b =>
                {
                    b.Navigation("Leaderboards");

                    b.Navigation("Tournaments");
                });
#pragma warning restore 612, 618
        }
    }
}
