// <auto-generated />
using System;
using DumpsterLeagueLeaderboard.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DumpsterLeagueLeaderboard.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260209014252_AddPlayerAndSeason")]
    partial class AddPlayerAndSeason
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DumpsterLeagueLeaderboard.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentDiscordId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_discord_id");

                    b.Property<string>("CurrentDiscordName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_discord_name");

                    b.Property<string>("CurrentIgn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_ign");

                    b.Property<int>("CurrentPoints")
                        .HasColumnType("integer")
                        .HasColumnName("current_points");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("DumpsterLeagueLeaderboard.Domain.Entities.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<DateTime>("SeasonEndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("season_end_date");

                    b.Property<string>("SeasonName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("season_name");

                    b.Property<DateTime>("SeasonStartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("season_start_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("seasons", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
